title: PUF Research
email: fei.hongming@u.nus.edu
description: >- # this means to ignore newlines until "baseurl:"
  In building...
baseurl: "/docs/" # the subpath of your site, e.g. /blog
url: "https://feihm-npu.github.io/docs" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
